apiVersion: v1
kind: Namespace
metadata:
  name: podstack-system
  labels:
    app.kubernetes.io/name: podstack
    app.kubernetes.io/part-of: podstack-inference-os
    podstack.io/component: system
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
