apiVersion: v1
kind: ServiceAccount
metadata:
  name: podstack-snapshot-agent
  namespace: serverless
  labels:
    app.kubernetes.io/name: podstack-snapshot-agent
    app.kubernetes.io/part-of: podstack-inference-os
    app.kubernetes.io/component: snapshot-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podstack-snapshot-agent
  namespace: serverless
  labels:
    app.kubernetes.io/name: podstack-snapshot-agent
    app.kubernetes.io/part-of: podstack-inference-os
    app.kubernetes.io/component: snapshot-agent
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podstack-snapshot-agent
  namespace: serverless
  labels:
    app.kubernetes.io/name: podstack-snapshot-agent
    app.kubernetes.io/part-of: podstack-inference-os
    app.kubernetes.io/component: snapshot-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podstack-snapshot-agent
subjects:
  - kind: ServiceAccount
    name: podstack-snapshot-agent
    namespace: serverless
