apiVersion: v1
kind: ServiceAccount
metadata:
  name: podstack-operator
  namespace: podstack-system
  labels:
    app.kubernetes.io/name: podstack-operator
    app.kubernetes.io/part-of: podstack-inference-os
    app.kubernetes.io/component: operator
    podstack.io/component: operator
