apiVersion: v1
kind: Service
metadata:
  name: podstack-proxy
  namespace: podstack-system
  labels:
    app.kubernetes.io/name: podstack-proxy
    app.kubernetes.io/part-of: podstack-inference-os
    app.kubernetes.io/component: proxy
    podstack.io/component: proxy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: podstack-proxy
    app.kubernetes.io/component: proxy
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
